print("helo its me sandip")
print("name: sandip")
print("age: 19")
print("location: kolkata")
print("hobby: coding")
print("fav food: biryani")
print("fav game: pubg")
print("fav movie: avengers")
print("fav song: tere liye")